version: "3"

services:
  registry:
    image: registry:2
    ports:
      - "443:5000"
      - "5000:5000"
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - ./reg_vol/:/var/lib/registry
      - ./certs/:/certs
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
      REGISTRY_HTTP_SECRET: 123456
